######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 23 14:37:54 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Person.h
SOURCES += main.cpp
