######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 24 08:59:13 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qlist1.cpp
