######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 24 06:11:39 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += car.h person.h
SOURCES += car.cpp main.cpp person.cpp
