######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 24 09:04:07 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qmap1.cpp
