################################################################################
#
# Makefile for the #include guard example
#
# Author: Jeff Shantz
#
# To build, simply type 'make'.  The program doesn't do anything, but without
# the include guard, it won't actually compile.
#
# To see what the include guards actually do, type 'g++ -E main.cpp'.  Then,
# take out the include guards in employee.h and person.h, and run 'g++ -E main.cpp'
# again.  Compare the results.
#
################################################################################

BIN=main

all: $(BIN)

main: 

clean:
	rm -f *.o

realclean: clean
	rm -f $(BIN)
