######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 24 09:01:37 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qlist2.cpp
